### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by lucianosousa**
testing against latest stable ruby versions

### CODE REVIEW

**Comment by rmm5t** [comment]
Can you please change these to `2.1` and `2.2` instead? Travis now supports less specific version designations so that we don't have to keep bumping these values for _patch_ level versions updates.

**Comment by lucianosousa** [comment]
ping @rmm5t can u merge this? :)

**Comment by rmm5t** [comment]
@lucianosousa Please change this to just `2.1` and `2.2`

**Comment by rmm5t** [comment]
Whoops. You did. My bad. ;-)

**Pull request merged**
