### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by VSPPedro**
🚀

### CODE REVIEW

**Review by mcmire — APPROVED** [review]
Good catch!

**Review by mcmire — APPROVED** [review]
LGTM!

**Comment by VSPPedro** [comment]
Hi @mcmire, hope you're doing great I don't have permission to merge in this repository. Letting you know in case you think I do.

**Comment by mcmire** [comment]
Hi @VSPPedro, sorry I didn't see this until now. You should have access now!

**Comment by VSPPedro** [comment]
No need for apologies. Thank you for the invitation, I will try to help with this project too.

**Pull request merged**
